#+TITLE: browser-history-backup
#+DATE: 2022-01-23T20:21:06+0800
#+AUTHOR: Jiacai Liu
#+LANGUAGE: cn
#+OPTIONS: toc:nil num:nil
#+STARTUP: content

#+begin_quote
All your history in one file.
#+end_quote

browser-history-backup is a command line tool to backup your different browser histories into one file, and visualize them!

* Features
- Rich dashboards to visualize your history
- Export as CSV file
- Entirely offline, No need to worry about privacy leaks
- Support Chrome/Firefox/Safari on macOS/Linux/Windows
- Well-designed schemas to avoid history duplication when backup multiple times
- No NPM, browser-history-backup is a single binary built mainly in Rust🦀

* Usage
#+begin_src bash
browser-history-backup 0.1.0

USAGE:
    browser-history-backup [OPTIONS] <SUBCOMMAND>

OPTIONS:
    -d, --db-file  <DB_FILE>           Database path [env: OH_DB_FILE=] [default: ~/browser-history-backup.db]
    -h, --help                         Print help information
    -v, --verbose
    -V, --version                      Print version information

SUBCOMMANDS:
    backup    Backup browser history to browser-history-backup
    export
    help      Print this message or the help of the given subcommand(s)
    serve     Start HTTP server to visualize history
    show      Show default history files on your computer
#+end_src
** Backup
#+begin_src bash
USAGE:
    browser-history-backup backup [OPTIONS]

OPTIONS:
    -d, --disable-detect
            Disable auto detect history files

    -D, --dry-run


    -f, --history-files <HISTORY_FILES>
            SQLite file path of different browsers(History.db/places.sqlite...)

    -h, --help
            Print help information
#+end_src
=backup= is the main subcommand, it will import browser history into browser-history-backup.

browser-history-backup will automatically detect history of different browsers by default, =show= subcommand will show what it can find.

Users can also use =-f= option to set other history files to backup, the history file has the following naming convention:
| Browser | History Filename |
|---------+------------------|
| Chrome  | History          |
| Firefox | places.sqlite    |
| Safari  | History.db       |
#+begin_src bash
# -f can be used multiple times
# -d is required when doing backup with browsers open
browser-history-backup backup -d -f ~/some-dir/History.db -f ~/another-dir/places.sqlite
#+end_src

** Serve
After backup browser history into browser-history-backup, the next step is to visualize those data.

=serve= subcommand will start a HTTP server at [[http://127.0.0.1:9960]], open this in your browser to explore.
* Installation
** Homebrew
#+begin_src bash
brew install browser-history-backup
#+end_src
** Binary
The [[https://github.com/Shaunakdas/browser-history-backup/releases][release page]] includes precompiled binaries for Linux, macOS and Windows.
** Cargo
#+begin_src bash
cargo install browser-history-backup
#+end_src


* Changelog
See [[file:CHANGELOG.org][CHANGELOG]]
* FAQ
- =Error code 5: The database file is locked= :: This error happens if your browser is opened during backup, as SQLite allow only one open connection.

  Close the browser is one solution, or you can copy history file to other directory other than default location.


* LICENSE
Copyright (c) 2022 Jiacai Liu <dev@liujiacai.net>

browser-history-backup is distributed under [[https://www.gnu.org/licenses/gpl-3.0.txt][GPL-3.0]] license.
